version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    image: sdorodniy/devops-for-programmers-project-74
    depends_on:
      - db
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
        - postgres:/var/lib/postgresql/data
volumes:
    postgres:
