services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: npm run dev
  caddy:
    image: caddy:2.6.4
    ports:
       - 80:80
       - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
