name: Build image

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: sdorodniy/devops-for-programmers-project-74

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_DATABASE_HOST: ${{ vars.DATABASE_HOST }}
          ENV_DATABASE_NAME: ${{ vars.DATABASE_NAME }}
          ENV_DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
          ENV_DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
      - name: build image
        run: make build
      - name: run tests
        run: make ci
      - name: push image
        run: make push
