name: Build image

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: sdorodniy/devops-for-programmers-project-74

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build image
        run: make build
      - name: run tests
        run: make ci
      - name: push image
        run: make push
